### ISSUE TITLE
ClockPicker: TODO List

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1428]
- [x] Look through PR's and apply appropriate patches: https://github.com/weareoutman/clockpicker/pulls
- [x] Theming (the component does not look right in dark themes)
- [x] AM/ PM (the clock supports AM/PM mode but its not implemented yet)
- [x] Styling (the fonts and styling are off)
- [x] Replace Bootstrap classes with custom CSS classes
- [x] Done button I have Localized as "Close" but it also does not look right and is not centered
- [x] Button mode like we have for time and calendar (not working currently)
- [x] Add client side callbacks like `beforeShow`
- [x] Add Ajax events like change or ValueChange
- [x] `PrimeFaces.skinInput` of the Input component.
- [x] HTMLInputText Attributes and InputRenderer
- [x] Register overlay scroll and resize listener to close the overlay if open
- [x] enable() and disable() widget methods
- [x] Test and enable working properly in Dialog

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/72ac1f09-65fc-4d61-9b25-71232e73dc1a)

cc @jxmai @jepsar 

Here is what ours currently looks like

![image](https://github.com/primefaces-extensions/primefaces-extensions/assets/4399574/1fdab994-f5b9-443e-bcb3-cece5d0c7440)

**Comment by jepsar** [comment]
Does "styling" also means adding dark mode support? Do you want me to have a look at those?

**Comment by jepsar** [comment]
I'll have a look at the styling and some other issues.

**Comment by melloware** [comment]
Thank you @jepsar

**Comment by jepsar** [comment]
After including the correct CSS it looks much better.

<img width="331" alt="Screenshot 2024-01-27 at 20 01 46" src="https://github.com/primefaces-extensions/primefaces-extensions/assets/7500178/eb8f2296-3187-4f91-b68a-a2cfd315a15b">

Maybe we should add darkmode in a new issue.

**Comment by melloware** [comment]
Looks way better!

**Comment by jepsar** [comment]
Also because I added ui-widget to the popup 😁

**Comment by melloware** [comment]
@jepsar did you push a commit I don't see any changes?

**Comment by melloware** [comment]
I just did some more refactoring to make it a more standard PF input type component

**Comment by jepsar** [comment]
I think I'll just push my changes (I didn't yet) and improve later (things like theme variable colors and dark mode).

**Comment by melloware** [comment]
I will take the AM/PM issue and looking through the open PRs issues

**Comment by jxmai** [comment]
I checked out the AM/PM issue and open a PR: https://github.com/primefaces-extensions/primefaces-extensions/pull/1431. This one is slightly more complicated than 24 hour format since Locale involves. Please take a look and let's see what you think.

**Comment by melloware** [comment]
I enhanced AM/PM to be locale aware so if you use `locale="es"` you will see it use "a.m." instead of "AM" for English etc.  Also fixed a few bugs in AM/PM handling and applied a few PR's I found

**Comment by jxmai** [comment]
> I enhanced AM/PM to be locale aware so if you use `locale="es"` you will see it use "a.m." instead of "AM" for English etc. Also fixed a few bugs in AM/PM handling and applied a few PR's I found

Cool fix :sunglasses:  (especially I saw javascript patches applied e.g. https://github.com/primefaces-extensions/primefaces-extensions/commit/2740f7c5af8a5e3f2aa7eb366178aef90c676d1f#diff-385b773093d6e9c4719ea68e3f552e3251c06b65e87a60921fa78f0028c66a4dR122-R135) to enable different locale of AM / PM

**Comment by melloware** [comment]
Next i need to test one in a dialog and apply some AppendTo patches I think so the popup displays properly inside a dialog.

**Comment by melloware** [comment]
OK dialog support added the last thing is the theme support @jepsar is handling.

**Comment by jepsar** [comment]
I hope that I can find some time to fix it this weekend.
